name: 'Deploy Cloudticon Github Action'
description: 'Deploy Cloudticon Github Action'
inputs:
  cloudticon_auth:
    description: 'cloudticon auth document'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cloudticon_auth}}
